version: "3.9"
networks:
  text_messenger:
    driver: bridge
services:
  textmessenger:
    image: ${DOCKER_REGISTRY-}textmessenger
    build:
      context: .
      dockerfile: TextMessenger/Dockerfile
    ports:
      - "80:80"
    networks:
      - text_messenger
    depends_on:
      - postgres_db_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
  postgres_db_container:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: text_messenger_db
    ports:
      - "5432:5432"
    networks:
      - text_messenger
    volumes:
      - postgres-data-db:/var/lib/postgresql/data
volumes:
  postgres-data-db:







